### ISSUE TITLE
Error event not working

### ISSUE THREAD

**Issue by mukeshprajapati-kombee** [vue-stripe/vuestripe.com#27]
` <stripe-element-card
                                class="company-card"
                                ref="elementRef"
                                :pk="pulishableKey"
                                :elementStyle="elementStyle"
                                @error="setStripeErrors"
                            >`
                            
Error event not emitting anything, I mean setStripeErrors not getting called

**Comment by jofftiquez** [comment]
Hello thanks, I will check it out.

**Comment by jofftiquez** [comment]
Hi, I'm gonna close this and move it to vue-stripe repo. Thanks.
