### ISSUE TITLE
Vue 3 Issue?

### ISSUE THREAD

**Issue by MikeThomasMakes** [vue-stripe/vuestripe.com#28]
I'm new at this and don't really know what I'm doing, but...

I'm trying to use vue-stripe with Vue 3 for a new custom website I'm building myself. I followed the instructions to install and import vue-stripe into my project and was met with this error:
![image](https://user-images.githubusercontent.com/8965099/128353944-c8b59fab-8082-4f4e-8e8d-f7a00ee11e42.png)

According to [this issue](https://github.com/vitejs/vite/issues/1973)  vite deprecated 'process.env' and replaced it with 'import.meta.env'. So in node_modules\@vue-stripe\vue-stripe\dist\index.js and vue-stripe.js, I replaced all instances of process.env with import.meta.env. That let to this error:
![image](https://user-images.githubusercontent.com/8965099/128355936-973204d6-7735-4e69-8006-5d41348129af.png)

From here I don't know what to do, as it seems like I'm trying to modify the library to work with Vue 3. Or I'm on the completely wrong path. No idea.

**Comment by jofftiquez** [comment]
Hello, @MikeThomasMakes thanks for bringing this up. Please refer to this issue for Vue 3 discussion https://github.com/vue-stripe/vuestripe.com/issues/28
