### ISSUE TITLE
Add Coupons & Taxes to subscriptions

### ISSUE THREAD

**Issue by Otto-munch** [vue-stripe/vuestripe.com#5]
It would be really nice to extend the integration with coupons and taxes. So far the documentation does not state how or if this integration is possible. Thank you for any help!

**Comment by jofftiquez** [comment]
Hello @Otto-munch thanks. This is noted, I will check if the feature has been implemented and deal with the docs accordingly.

**Comment by jofftiquez** [comment]
Created a new issue related to this. https://github.com/vue-stripe/vue-stripe/issues/183

**Comment by jofftiquez** [comment]
Referencing this: https://github.com/vue-stripe/vue-stripe/issues/183#issuecomment-815371318
