### ISSUE TITLE
Missing 404 Page

### ISSUE THREAD

**Issue by deidyomega** [vue-stripe/vuestripe.com#51]
Your 404 page is just "Error".

https://vuestripe.com/lol

Should be cleaned up, and have the standard navbar, and maybe a helpful message, or bad meme.

**Comment by jofftiquez** [comment]
> Your 404 page is just "Error".
> 
> [vuestripe.com/lol](https://vuestripe.com/lol)
> 
> Should be cleaned up, and have the standard navbar, and maybe a helpful message, or bad meme.

Hey man, appreciate the issue. I'm not sure if I need to add this still coz this website will be replaced soon together with the release of version 5 🤔 I'll check what I can do as soon as I'm not busy. 

A bad meme is a good idea 💪

**Comment by jofftiquez** [comment]
Closing this as version 5 is coming soon. See the latest commits [here](https://github.com/vue-stripe/vuestripe.com/commits/major/version-5). Thanks again!
