### ISSUE TITLE
Token not getting returned

### ISSUE THREAD

**Issue by sillvva** [vue-stripe/vuestripe.com#6]
I've set up the element per the instructions on the website, however, a token is not getting generated as the element is loaded or as I fill out the form.

```
<stripe-element-card
  ref="cardRef"
  :pk="stripeKey"
  v-if="stripeKey"
  @token="tokenCreated"
/>
```

The element loads fine, using my test key, but tokenCreated never triggers. I even put a console.log to watch for the event trigger. What am I doing wrong?

**Comment by jofftiquez** [comment]
Hello @sillvva may I see your code? Thanks.

**Comment by sillvva** [comment]
Hi! And thanks! The code is here.

https://github.com/sillvva/mattdekok.dev/blob/master/frontend/pages/donate/index.vue

The element is on line 42. I query the public key from a Firebase function, and then store the key in asyncData. The element does load, but the @token event does nothing as I fill out the form.

**Comment by sillvva** [comment]
Looks like it was private. I've set the repo to public.

**Comment by jofftiquez** [comment]
Hello @sillvva let me inspect. Thanks.

**Comment by jofftiquez** [comment]
Hello again @sillvva it looks like you are missing a step, specifically, the step to trigger the process of generating the token. I updated the example code here https://vuestripe.com/stripe-elements/card

Also, for your convenience I created a PR that fixed the problem. Sorry I missed that one in the documentation.

PR https://github.com/sillvva/mattdekok.dev/pull/20

**Comment by sillvva** [comment]
Excellent! It works. Thank you! 😁

**Comment by jofftiquez** [comment]
@sillvva you can close this if there's no more issue. Thanks.
