### ISSUE TITLE
Stripe Elements Plugin example code extra closing parenthesis

### ISSUE THREAD

**Issue by Sooshiii** [vue-stripe/vuestripe.com#7]
The example on `/pages/stripe-elements/plugin.vue` has the code
`<button id="custom-button" @click="createToken")>Generate Token</button>`
The closing parenthesis causes it to fail. Should instead be:
`<button id="custom-button" @click="createToken">Generate Token</button>`

**Comment by jofftiquez** [comment]
Thank you, this is noted.
