### ISSUE TITLE
Funny font

### ISSUE THREAD

**Issue by BarnabasSzabolcs** [vue-stripe/vuestripe.com#8]
Hi! 
Awesome documentation, and the Squigly font is pretty funny but I have to disable it manually because it is so hard to read for me. I'd love a switch for disabled people like me.

Love the real hamburger menu's though!
Best,
Barney

**Comment by jofftiquez** [comment]
Hello, @BarnabasSzabolcs thanks for the feedback. I didn't really think about the effects of the font style to the accessibility, sorry about that. I will update this soon. 😃 🙇🏽‍♂️

**Comment by BarnabasSzabolcs** [comment]
Joff, 
I felt sad that I wrote to kill a unique feature of something, 
and I had a hunch you guys are pretty creative, so I have looked at your personal home page 
and I loved it, the whole concept with the command line!

I've found vuestripe.com via this article:
https://randomcodetips.com/recurring-stripe-checkout-payment-in-vue-js/
and I think it is a great tutorial for how to use your plugin, it may be worth linking to it.

**Comment by jofftiquez** [comment]
No problem at all @BarnabasSzabolcs :) Thank you for checking my profile. 😀

**Comment by jofftiquez** [comment]
@BarnabasSzabolcs I did a quick research about this and I found out that `Open Sans` might be a good option. Let me know if the new update is fine. Thanks.

**Comment by BarnabasSzabolcs** [comment]
Open Sans is fine, too, thanks! 

I just checked, thanks a lot!
